<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Tuilow.Learning.Domain</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\Tuilow.SharedKernel.Domain\Tuilow.SharedKernel.Domain.csproj" />
  </ItemGroup>
</Project>
