<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HiMentor.Channel.Api</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HiMentor.Channel.Application\HiMentor.Channel.Application.csproj" />
    <ProjectReference Include="..\HiMentor.Channel.Infrastructure\HiMentor.Channel.Infrastructure.csproj" />
  </ItemGroup>
</Project>
